In [4]:
import numpy as np
A = np.array([[5,3],[3,2]])
B = np.array([[2,1],[1,4]])
print(A)
print(B)

[[5 3]
 [3 2]]
[[2 1]
 [1 4]]


In [17]:
C = A.dot(B)
print(C)

[[13 17]
 [ 8 11]]


In [10]:
def check_symmetric(a, rtol=1e-05, atol=1e-08):
    return np.allclose(a, a.T, rtol=rtol, atol=atol)

check_symmetric(C)
(C==C.T).all()

False

In [11]:
np.linalg.inv(C)

array([[ 1.57142857, -2.42857143],
       [-1.14285714,  1.85714286]])

In [14]:
1/7 * C

array([[1.85714286, 2.42857143],
       [1.14285714, 1.57142857]])

In [19]:
np.linalg.eig(C).eigenvectors

array([[ 0.84621048, -0.80102339],
       [ 0.53284878,  0.59863305]])

In [32]:
empty_set = set()
for i in range(1,5):
    for j in range(1,5):
        if j > i:
            empty_set.add(i*i + j*j)
            print(f"i: {i}, j: {j}, sum: {i*i + j*j}")

print(sorted(empty_set))

i: 1, j: 2, sum: 5
i: 1, j: 3, sum: 10
i: 1, j: 4, sum: 17
i: 2, j: 3, sum: 13
i: 2, j: 4, sum: 20
i: 3, j: 4, sum: 25
[5, 10, 13, 17, 20, 25]
